// Generated by scripts/build_large_airports.py -- do not edit.
// Source:   https://github.com/davidmegginson/ourairports-data
// Commit:   79efa72ec1e344d91b081160634fa042a56a21b8
// Date:     2026-06-08T01:53:13Z
// airports.csv  SHA-256: 092223c8d6a1cf60c13d450e61a91438cc80c5fd50f92f52f49a38826e04a354
//             length:  12651071
//             git blob 1df8da39141e2e6adb3c8439b684579da97c19a8
// runways.csv   SHA-256: 312f9ded8a5a29f8634bd615b0a7aadd4ed01e773ae63e5aab7c510629440fec
//             length:  3951490
//             git blob d8fdbbe9a1f7d47ee78eade1ec30f020e3cc9e7d
// License: Public Domain / The Unlicense  https://raw.githubusercontent.com/davidmegginson/ourairports-data/79efa72ec1e344d91b081160634fa042a56a21b8/LICENSE
// Filter schema version: 1
// Filter: type=large_airport, 4-char ICAO ident, open runways,
//         helipads excluded, coordinates and runway endpoints required.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::large_airports {

struct Airport {
  char ident[5];
  int32_t lat_e7;
  int32_t lon_e7;
};

struct Runway {
  uint16_t airport_idx;
  int32_t le_lat_e7;
  int32_t le_lon_e7;
  int32_t he_lat_e7;
  int32_t he_lon_e7;
  uint16_t length_m;
};

constexpr size_t kAirportCount = 1166;
constexpr size_t kRunwayCount = 1706;

extern const Airport kAirports[kAirportCount];
extern const Runway kRunways[kRunwayCount];

}  // namespace data::large_airports
